services:
  server:
    build: ./Server
    env_file:
      - ./Server/.env
    container_name: yelpcamp-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  client:
    build: ./Client
    container_name: yelpcamp-client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

  mongo:
    image: mongo:6
    container_name: yelpcamp-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
